/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "id" {
  description = <<-EOT
    AWS Region in which logging is configured.
  EOT
  value       = aws_bedrock_model_invocation_logging_configuration.this.id
}

output "logging_config" {
  description = <<-EOT
    The complete logging configuration that was applied.
  EOT
  value       = aws_bedrock_model_invocation_logging_configuration.this.logging_config
}

output "s3_bucket_name" {
  description = <<-EOT
    The S3 bucket name used for logging (if S3 config is enabled).
  EOT
  value       = var.logging_config.s3_config != null ? var.logging_config.s3_config.bucket_name : null
}

output "s3_key_prefix" {
  description = <<-EOT
    The S3 key prefix used for logging (if S3 config is enabled).
  EOT
  value       = var.logging_config.s3_config != null ? var.logging_config.s3_config.key_prefix : null
}

output "cloudwatch_log_group_name" {
  description = <<-EOT
    The CloudWatch log group name used for logging (if CloudWatch config is enabled).
  EOT
  value       = var.logging_config.cloudwatch_config != null ? var.logging_config.cloudwatch_config.log_group_name : null
}

output "cloudwatch_role_arn" {
  description = <<-EOT
    The IAM role ARN used for CloudWatch logging (if CloudWatch config is enabled).
  EOT
  value       = var.logging_config.cloudwatch_config != null ? var.logging_config.cloudwatch_config.role_arn : null
}

output "large_data_s3_bucket_name" {
  description = <<-EOT
    The S3 bucket name used for large data delivery (if configured).
  EOT
  value = (
    var.logging_config.cloudwatch_config != null &&
    var.logging_config.cloudwatch_config.large_data_delivery_s3_config != null
  ) ? var.logging_config.cloudwatch_config.large_data_delivery_s3_config.bucket_name : null
}

output "data_delivery_settings" {
  description = <<-EOT
    Summary of data delivery settings configured.
  EOT
  value = {
    embedding_data_delivery_enabled = var.logging_config.embedding_data_delivery_enabled
    image_data_delivery_enabled     = var.logging_config.image_data_delivery_enabled
    text_data_delivery_enabled      = var.logging_config.text_data_delivery_enabled
    video_data_delivery_enabled     = var.logging_config.video_data_delivery_enabled
    s3_enabled                      = var.logging_config.s3_config != null
    cloudwatch_enabled              = var.logging_config.cloudwatch_config != null
    large_data_delivery_enabled     = (
      var.logging_config.cloudwatch_config != null &&
      var.logging_config.cloudwatch_config.large_data_delivery_s3_config != null
    )
  }
}
