/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "logging_config" {
  type = object({
    embedding_data_delivery_enabled = optional(bool, true)
    image_data_delivery_enabled     = optional(bool, true)
    text_data_delivery_enabled      = optional(bool, true)
    video_data_delivery_enabled     = optional(bool, true)
    
    s3_config = optional(object({
      bucket_name = string
      key_prefix  = optional(string)
    }))
    
    cloudwatch_config = optional(object({
      log_group_name = string
      role_arn      = optional(string)
      large_data_delivery_s3_config = optional(object({
        bucket_name = string
        key_prefix  = optional(string)
      }))
    }))
  })
  description = <<-EOT
    The logging configuration values to set for Bedrock model invocation logging.
    
    embedding_data_delivery_enabled: Set to include embeddings data in the log delivery (default: true)
    image_data_delivery_enabled: Set to include image data in the log delivery (default: true)
    text_data_delivery_enabled: Set to include text data in the log delivery (default: true)
    video_data_delivery_enabled: Set to include video data in the log delivery (default: true)
    
    s3_config: S3 configuration for storing log data
    - bucket_name: S3 bucket name (required)
    - key_prefix: S3 prefix for log objects (optional)
    
    cloudwatch_config: CloudWatch logging configuration
    - log_group_name: CloudWatch log group name (required)
    - role_arn: IAM role ARN for CloudWatch access (optional)
    - large_data_delivery_s3_config: S3 config for large data delivery
      - bucket_name: S3 bucket name for large data (required)
      - key_prefix: S3 prefix for large data objects (optional)
    
    Note: Either s3_config or cloudwatch_config (or both) must be specified.
  EOT

  validation {
    condition = (
      var.logging_config.s3_config != null ||
      var.logging_config.cloudwatch_config != null
    )
    error_message = "At least one of s3_config or cloudwatch_config must be specified."
  }
}
