/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "guardrail_id" {
  description = <<-EOT
    The unique identifier of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.guardrail_id
}

output "guardrail_arn" {
  description = <<-EOT
    The Amazon Resource Name (ARN) of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.guardrail_arn
}

output "name" {
  description = <<-EOT
    The name of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.name
}

output "description" {
  description = <<-EOT
    The description of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.description
}

output "version" {
  description = <<-EOT
    The version of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.version
}

output "status" {
  description = <<-EOT
    The status of the guardrail.
  EOT
  value       = aws_bedrock_guardrail.this.status
}

output "created_at" {
  description = <<-EOT
    The date and time at which the guardrail was created.
  EOT
  value       = aws_bedrock_guardrail.this.created_at
}

output "tags_all" {
  description = <<-EOT
    A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
  EOT
  value       = aws_bedrock_guardrail.this.tags_all
}
