/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "arn" {
  description = <<-EOT
    The Amazon Resource Name (ARN) of the inference profile.
  EOT
  value       = aws_bedrock_inference_profile.this.arn
}

output "id" {
  description = <<-EOT
    The unique identifier of the inference profile.
  EOT
  value       = aws_bedrock_inference_profile.this.id
}

output "name" {
  description = <<-EOT
    The name of the inference profile.
  EOT
  value       = aws_bedrock_inference_profile.this.name
}

output "description" {
  description = <<-EOT
    The description of the inference profile.
  EOT
  value       = aws_bedrock_inference_profile.this.description
}

output "status" {
  description = <<-EOT
    The status of the inference profile. ACTIVE means that the inference 
    profile is available to use.
  EOT
  value       = aws_bedrock_inference_profile.this.status
}

output "type" {
  description = <<-EOT
    The type of the inference profile. SYSTEM_DEFINED means that the inference 
    profile is defined by Amazon Bedrock. APPLICATION means that the inference 
    profile is defined by the user.
  EOT
  value       = aws_bedrock_inference_profile.this.type
}

output "models" {
  description = <<-EOT
    A list of information about each model in the inference profile.
  EOT
  value       = aws_bedrock_inference_profile.this.models
}

output "created_at" {
  description = <<-EOT
    The time at which the inference profile was created.
  EOT
  value       = aws_bedrock_inference_profile.this.created_at
}

output "updated_at" {
  description = <<-EOT
    The time at which the inference profile was last updated.
  EOT
  value       = aws_bedrock_inference_profile.this.updated_at
}

output "tags_all" {
  description = <<-EOT
    A map of tags assigned to the resource, including those inherited from 
    the provider default_tags configuration block.
  EOT
  value       = aws_bedrock_inference_profile.this.tags_all
}
