/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "name" {
  type        = string
  description = <<-EOT
    The name of the inference profile. Must be unique within the AWS account.
    This name will be used to identify the profile for cost allocation and monitoring.
  EOT
}

variable "model_source" {
  type = object({
    copy_from = string
  })
  description = <<-EOT
    The source of the model this inference profile will track metrics and cost for.
    
    copy_from: The Amazon Resource Name (ARN) of the model. This can be either:
    - A foundation model ARN (e.g., "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0")
    - An inference profile ARN from another account (e.g., "arn:aws:bedrock:eu-central-1:123456789012:inference-profile/eu.anthropic.claude-3-5-sonnet-20240620-v1:0")
  EOT
}

variable "description" {
  type        = string
  description = <<-EOT
    The description of the inference profile. Provides context about the purpose
    and usage of this profile for cost allocation and monitoring.
  EOT
  default     = null
}

variable "tags" {
  type        = map(string)
  description = <<-EOT
    Key-value mapping of resource tags for the inference profile. These tags
    are essential for cost allocation, project tracking, and resource management.
    Common tags include ProjectID, Environment, Team, CostCenter, etc.
  EOT
  default     = {}
}

variable "timeouts" {
  type = object({
    create = optional(string, "5m")
    update = optional(string, "5m")
    delete = optional(string, "5m")
  })
  description = <<-EOT
    Configuration options for timeouts.
    
    create: Timeout for creating the inference profile (default: 5m)
    update: Timeout for updating the inference profile (default: 5m)
    delete: Timeout for deleting the inference profile (default: 5m)
  EOT
  default     = null
}
