/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "arn" {
  description = "The ARN of the CloudWatch alarm"
  value = try(
    aws_cloudwatch_metric_alarm.this[0].arn,
    aws_cloudwatch_composite_alarm.this[0].arn,
    aws_cloudwatch_metric_alarm.anomaly[0].arn,
    ""
  )
}

output "id" {
  description = "The ID of the CloudWatch alarm"
  value = try(
    aws_cloudwatch_metric_alarm.this[0].id,
    aws_cloudwatch_composite_alarm.this[0].id,
    aws_cloudwatch_metric_alarm.anomaly[0].id,
    ""
  )
}

output "alarm_name" {
  description = "The name of the alarm"
  value = try(
    aws_cloudwatch_metric_alarm.this[0].alarm_name,
    aws_cloudwatch_composite_alarm.this[0].alarm_name,
    aws_cloudwatch_metric_alarm.anomaly[0].alarm_name,
    ""
  )
}

output "alarm_description" {
  description = "The description of the alarm"
  value = try(
    aws_cloudwatch_metric_alarm.this[0].alarm_description,
    aws_cloudwatch_composite_alarm.this[0].alarm_description,
    aws_cloudwatch_metric_alarm.anomaly[0].alarm_description,
    ""
  )
}

# Metric alarm specific outputs
output "metric_alarm_arn" {
  description = "The ARN of the metric alarm"
  value       = try(aws_cloudwatch_metric_alarm.this[0].arn, "")
}

output "metric_alarm_id" {
  description = "The ID of the metric alarm"
  value       = try(aws_cloudwatch_metric_alarm.this[0].id, "")
}

# Composite alarm specific outputs
output "composite_alarm_arn" {
  description = "The ARN of the composite alarm"
  value       = try(aws_cloudwatch_composite_alarm.this[0].arn, "")
}

output "composite_alarm_id" {
  description = "The ID of the composite alarm"
  value       = try(aws_cloudwatch_composite_alarm.this[0].id, "")
}

# Anomaly alarm specific outputs
output "anomaly_alarm_arn" {
  description = "The ARN of the anomaly alarm"
  value       = try(aws_cloudwatch_metric_alarm.anomaly[0].arn, "")
}

output "anomaly_alarm_id" {
  description = "The ID of the anomaly alarm"
  value       = try(aws_cloudwatch_metric_alarm.anomaly[0].id, "")
}

output "anomaly_detector_arn" {
  description = "The ARN of the anomaly detector (if supported)"
  value       = ""
}

output "anomaly_detector_id" {
  description = "The ID of the anomaly detector (if supported)"
  value       = ""
}

# Complete alarm objects
output "metric_alarm" {
  description = "Complete metric alarm object"
  value       = try(aws_cloudwatch_metric_alarm.this[0], {})
  sensitive   = true
}

output "composite_alarm" {
  description = "Complete composite alarm object"
  value       = try(aws_cloudwatch_composite_alarm.this[0], {})
  sensitive   = true
}

output "anomaly_alarm" {
  description = "Complete anomaly alarm object"
  value       = try(aws_cloudwatch_metric_alarm.anomaly[0], {})
  sensitive   = true
}

output "anomaly_detector" {
  description = "Complete anomaly detector object (if supported)"
  value       = {}
  sensitive   = true
}
