/**
  * <!-- Module outputs go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

output "version" {
  description = <<-EOT
    The version number of the guardrail version.
  EOT
  value       = aws_bedrock_guardrail_version.this.version
}

output "guardrail_arn" {
  description = <<-EOT
    The Amazon Resource Name (ARN) of the guardrail.
  EOT
  value       = aws_bedrock_guardrail_version.this.guardrail_arn
}

output "description" {
  description = <<-EOT
    The description of the guardrail version.
  EOT
  value       = aws_bedrock_guardrail_version.this.description
}

output "skip_destroy" {
  description = <<-EOT
    Whether the guardrail version will be retained during destroy operations.
  EOT
  value       = aws_bedrock_guardrail_version.this.skip_destroy
}

output "id" {
  description = <<-EOT
    The ID of the guardrail version resource.
  EOT
  value       = aws_bedrock_guardrail_version.this.id
}
