/**
  * <!-- Module variables go here.
  *      Always include descriptions as they will populate
  *      autogenerated documentation. -->
*/

variable "guardrail_arn" {
  type        = string
  description = <<-EOT
    Guardrail ARN. This is the Amazon Resource Name of the guardrail for which 
    you want to create a version.
  EOT
}

variable "description" {
  type        = string
  description = <<-EOT
    Description of the Guardrail version. Provides context about what changes 
    or improvements are included in this version.
  EOT
  default     = null
}

variable "skip_destroy" {
  type        = bool
  description = <<-EOT
    Whether to retain the old version of a previously deployed Guardrail when 
    this resource is destroyed. When set to true, the guardrail version will 
    not be deleted during terraform destroy operations. Default is false.
  EOT
  default     = false
}

variable "timeouts" {
  type = object({
    create = optional(string, "5m")
    delete = optional(string, "5m")
  })
  description = <<-EOT
    Configuration options for timeouts.
    
    create: Timeout for creating the guardrail version (default: 5m)
    delete: Timeout for deleting the guardrail version (default: 5m)
  EOT
  default     = null
}
